### ISSUE TITLE
PyPI is missing 1.5.1

### ISSUE THREAD

**Issue by mtelka** [stefanholek/lazy#14]
There is the [1.5.1](https://github.com/stefanholek/lazy/releases/tag/1.5.1) tag in git, but [PyPI](https://pypi.org/project/lazy/) is missing the release.  Please add `1.5.1` to PyPI.  Thank you.

**Comment by stefanholek** [comment]
The 1.5.1 tags was meant for readthedocs only. Lazy 1.6 has been released.
