### ISSUE TITLE
Add LICENSE file containing 2, 3 or 4-clause BSD License text

### ISSUE THREAD

**Issue by koobs** [stefanholek/lazy#2]
Add a LICENSE file to the repository containing the chosen license text, to indicate explicitly which of the BSD Licenses [1] is specified:
- 2-clause ("Simplified" or "FreeBSD")
- 3-clause ("Revised", "New" or "Modified"), or
- 4-clause ("Original")

I am currently creating a FreeBSD Port for the lazy package, and need to specify this for our license framework requirements.
- Update Trove classifiers to suite (for bonus points)

[1] https://en.wikipedia.org/wiki/BSD_licenses

**Comment by jakirkham** [comment]
Could you please tell us the answer to this question, @stefanholek?

**Comment by jakirkham** [comment]
cc @pmlandwehr

**Comment by jakirkham** [comment]
Any thoughts on this @stefanholek? Would love to distribute this software, but this is really a problem for us.

**Comment by jakirkham** [comment]
Friendly nudge @stefanholek . Hoping this is an easy question.

**Comment by stefanholek** [comment]
Fixed in 1.3.

**Comment by jakirkham** [comment]
Thank you.

**Comment by jakirkham** [comment]
Also would be good to add this to `MANIFEST.in` so the license is packaged in future releases as is proposed in PR ( https://github.com/stefanholek/lazy/pull/5 ).
