### ISSUE TITLE
Feature request: invalidate_all

### ISSUE THREAD

**Issue by brandonscript** [stefanholek/lazy#8]
Just discovered that you can invalidate (it's not in the main README!), but it would be handy to be able to enumerate all lazy properties on a class instance and invalidate them. If you're open to the idea, I might work on a PR to accomplish it.

**Comment by stefanholek** [comment]
This is possible but may become expensive if the involved classes have lots of attributes.
See for example https://github.com/stefanholek/lazy/blob/main/lazy/tests/test_lazy.py#L323

However I do not plan to add any new APIs or features to lazy.
